version: '3.8'

services:
  troapi_db:
    image: postgis/postgis:12-master
    container_name: troapi_db
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    volumes:
      - troapi_db_data:/var/lib/postgresql/data/
  troapi:
    build: .
    image: ${API_IMAGE}
    container_name: troapi
    command: sh -c "/wait && ./entrypoint.sh && gunicorn --bind 0.0.0.0:8000 troapi:app"
    restart: ${RESTART_POLICY}
    ports:
      - "8000"
    environment:
      - WAIT_HOSTS=troapi_db:5432
      - WAIT_TIMEOUT=60
      - SQLALCHEMY_DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@troapi_db:5432/${DB_NAME}
      - FLASK_APP=troapi/__init__.py
      - MEDIA_URL=${MEDIA_URL}
    volumes:
      - ${UPLOADS_VOLUME}:/usr/src/app/uploads
    depends_on:
      - troapi_db
  troapi_nginx:
    image: nginx:1.18.0-alpine
    restart: ${RESTART_POLICY}
    container_name: troapi_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${UPLOADS_VOLUME}:/troapi/media
    ports:
      - ${NGINX_PORT}:80
volumes:
  troapi_db_data: