"""add jtwc source

Revision ID: 463275905311
Revises: 22cf38e05c49
Create Date: 2022-10-04 18:32:52.402723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463275905311'
down_revision = '22cf38e05c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storm', sa.Column('jtwc_source', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storm', 'jtwc_source')
    # ### end Alembic commands ###
