"""add storm plot

Revision ID: a4dd4a766d5e
Revises: 951006d415e9
Create Date: 2022-10-17 10:53:25.870890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dd4a766d5e'
down_revision = '951006d415e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storm_plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storm_id', sa.String(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('plot_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['storm_id'], ['storm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storm_plot')
    # ### end Alembic commands ###
